# Generated by Django 2.2.2 on 2020-03-20 12:04

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0002_auto_20200317_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='meta',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='meta data integrate import lib'),
        ),
    ]
