# Generated by Django 2.2.2 on 2020-06-22 17:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0003_dataimporttemporary_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimporttemporary',
            name='data',
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='info_import_file',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Info import file'),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='json_data_path',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='log',
            field=models.TextField(default=None, null=True, verbose_name='log import data file'),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='temp_file_path',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='time_exc',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='total_process',
            field=models.IntegerField(default=0, verbose_name='Total process record by status'),
        ),
        migrations.AlterField(
            model_name='dataimporttemporary',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
