# Generated by Django 2.2.2 on 2020-06-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0004_auto_20200623_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimporttemporary',
            name='json_data_path',
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='json_data',
            field=models.TextField(default=None, null=True),
        ),
    ]
