# Generated by Django 2.2.2 on 2020-07-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0006_auto_20200702_1747'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asintest',
            unique_together={('profile_id', 'brand', 'asin')},
        ),
    ]
