# Generated by Django 2.2.2 on 2020-07-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0007_auto_20200708_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='temp_file_path_type',
            field=models.CharField(choices=[('google', 'Google Storage'), ('local', 'Local storage')], default='local', max_length=20, verbose_name='Temp file path type'),
        ),
    ]
