# Generated by Django 2.2.2 on 2020-07-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0008_dataimporttemporary_temp_file_path_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='json_data_last_cache',
            field=models.TextField(default='{}', null=True, verbose_name='Json Data Last Cache'),
        ),
        migrations.AlterField(
            model_name='dataimporttemporary',
            name='json_data',
            field=models.TextField(default='{}', null=True, verbose_name='Json Data Origin'),
        ),
    ]
