# Generated by Django 2.2.2 on 2020-10-19 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plat_import_lib_api', '0009_auto_20200729_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimporttemporary',
            name='process_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='process_started',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='validation_completed',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dataimporttemporary',
            name='validation_started',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
